# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

url: https://thysbelon.github.io

permalink: /:year/:month/:day/:title

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default-en"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-en"
      excerpt_separator: <!--more-->
  
# Build settings
plugins:
   - jekyll-postfiles
   - jekyll-paginate-v2
   - jekyll-archives
   #  - jekyll-feed
   - jekyll-minifier

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
#  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

jekyll-minifier:
  compress_javascript: false
  compress_json: false
  exclude: 
    - 'atom-en.xml'
    - 'atom-jp.xml'
  uglifier_args:
    harmony: true
   
jekyll-archives:
  slug_mode: raw
  enabled: all
  layout: archive
  layouts:
    day: redir2mon
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/Tags/:name'
    category: '/Categories/:name'


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
